version: "2.1"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        container_name: elasticsearch
        expose:
            - 9200
            - 9300
        environment: 
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    kibana:
        build:
            context: kibana
            dockerfile: Dockerfile
        container_name: kibana
        ports:
            - 5601:5601
        depends_on: 
            - elasticsearch
    spark:
        build: 
            context: spark
            dockerfile: Dockerfile
        ports:
            - 4040:4040
        container_name: spark